/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Azamuki (https://sketchfab.com/Azamuki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-in-love-f39ce19b92e246268f4c501b72ea7d0e
Title: Heart in Love
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Heart = (props) => {
  

  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/heart_in_love.glb`)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Heart_Heart_0.geometry}
        material={materials.Heart}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Marble_Marble_0.geometry}
        material={materials.Marble}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/heart_in_love.glb`)
export default Heart
